# Generated by Django 3.2.17 on 2023-02-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Movie',
        ),
    ]
