# Generated by Django 3.2.17 on 2023-02-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_auto_20230205_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_reting',
            new_name='number_rating',
        ),
    ]
